name: tabletop_exercise_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  get: 4.6.5
  google_fonts: 3.0.1
  matrix_gesture_detector: ^0.1.0
  simple_gradient_text: 1.2.3
  url_launcher: ^6.1.5
  lottie: 1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/exercise/
    - assets/lottie/
  uses-material-design: true
